
# ASCII: É UMA FORMA DE DAR VALORES NUMERICOS PARA CHARACTERES NO CASO LETRAS E PONTUAÇÕES E SIMBOLOS, ASCII É
# UMA TABELA QUE ASSOCIA VALORES NUMERICOS AOS CHARACTERES.

# CHAR: CHAR É ABREVIAÇÃO DE CHARACTER, EM LINGUAGEM UM POUCO MAIS BAIXO NIVEL É NESCESSARIA PASSAR O TIPO DE DADO
# QUE IRA SER ARMAZENADO NA VARIAVEL E O CHAR É PASSADO PARA REPRESENTAR UMA LETRA NA VARIAVEL

# UMA FORMA DE CONVERTER UM CONJUNTO DE CHAR(CHARACERES, LETRAS SIMBOLOS OU PONTUAÇÕES) EM VALORES NUMERICOS
# ASSCIADOS A ELES NA TABELA ASCII, É USANDO O ord() PARA OBTER UM VALOR NUMERICO ASSOCIADO A UMA STRING OU UM CHAR

# JÁ PARA OBTER O CHARACTER(LETRA, SIMBOLO OU PONTUAÇÃO) DE UM VALOR NUMERICO DA TABELA ASCII É USANDO O: chr()

str_char = input("digite o valor char ou string para ser convertido em valor associado a ele na tabela ascii:")

ascii_values = []
for char in str_char:
	ascii_values.append(ord(char))

print(ascii_values)


