// MY FIRST PROGRAM C++
// C++ IS A LANGUAGE: COMPILED, MULTIPARADIGM, IMPERATIVE, FUNCTIONAL
// FITS FOR: MOBILE, GENERIC, AND THROUGH OTHER

#include <iostream> // INSTRUE THE COMPILER FOR INCLUDE THE LIBARY STANDARD FOR HANDLING INPUT AND OUTPUT OF DATA IN PROGRAM

// int: INDICATE THAT THE FUNCTION MAIN WILL RETURN CODE INTEGER FOR SYSTEM OPERATIONAL WHEN PROGRAM EXECUTE WITH SUCEFULL.
int main() {
    std::cout << "Hello World!!!\n"; // DIRECTLLY THE VALUE "Hello World!!!" FOR OUTPUT STANDARD: CONSOLE TERMINAL std::cout AND std::end1 IS OBJECT OF CLASS INSTANCE std::ostream OF THE LIBARY iostream std::cout IS STANDARD OUTPUT OF THE SYSTEM AND std::end1 INSERT A NEW LINE << USED FOR DIRECTLY THE STRING FOR std::cout and INSERT std::end1 TO THE END OF STRING
    return 0; // REUTURN INT STATUS CODE FOR SYSTEM, INDICATE THAT THE FUNCTION BE EXECUTED WITH SUCESS
}
