string_ex = "Hello World, Olá Mundo"


# OBTEM OS CARACTERES DA POSIÇÃO 14 EM DIANTE, E CORTA OS CARACTERES ANTES DA POSIÇÃO 14
print(string_ex[14:])

# OBTEM OS CARACTRES DA POSIÇÃO 0 ATÉ A 14, E CORTA OS CARACTERES POSTERIORES DA POSIÇÃO 14
print(string_ex[:14])
